### ISSUE TITLE
Crusaders Crossbow lag

### ISSUE THREAD

**Issue by ChaseTownsend** [kurwabomber/Incremental-Fortress#23]
With a bunch or projectiles either rendered or hitting stuff it cause the server and client to lag massivly maybe nerf the firerate or clipsize
or find ways to prevent so much lag

**Comment by kurwabomber** [comment]
crusader's crossbow now has an additional damage mult (which makes it better starting off) but has a max fire rate of only 7x now. 
it now has 22rps without any buffs and 33rps with agility.
