### ISSUE TITLE
Maelstrom charge projectile speed bug

### ISSUE THREAD

**Issue by ChaseTownsend** [kurwabomber/Incremental-Fortress#27]
With the milk Jar (might also happen with jarate) the Maelstrom charge causes the projectiles speed to be set to 0 even though the Maelstrom charge tweak on the page does not explain any change to its projectile speed

**Comment by kurwabomber** [comment]
more clarification on what exactly is happening? is it the jars projectile speed not working?

**Comment by ChaseTownsend** [comment]
Sorry the Maelstrom charge Just removes its projectile speed
