### ISSUE TITLE
GasPasser's immolation recharge bug

### ISSUE THREAD

**Issue by ChaseTownsend** [kurwabomber/Incremental-Fortress#28]
after activating immolation it can sometimes not come back after recharge. only using immolation tweak seems to cause this.
This is likely happening with how much it recharges with high enough damage ticks

**Comment by kurwabomber** [comment]
vanilla tf2 bug with high recharge rate, not sure how to fix right now

**Comment by ChaseTownsend** [comment]
it also happens at -90% recharge rate

**Comment by ChaseTownsend** [comment]
nevermind its just immolation tweak breaking it from what i found

**Comment by kurwabomber** [comment]
should be fixed in next update
