### ISSUE TITLE
Disguising Can sometimes give the disguises current weapon????

### ISSUE THREAD

**Issue by ChaseTownsend** [kurwabomber/Incremental-Fortress#31]
the title says it all and this randomly happened when i disguised and firing the new weapon wont undisguised the player
This seems to happen with the liberty launcher robots
![20240616165946_1](https://github.com/kurwabomber/Incremental-Fortress/assets/110744155/3e6e99d0-b96d-47f7-84a0-115331bf8a74)

**Comment by ChaseTownsend** [comment]
![20240616165946_1](https://github.com/kurwabomber/Incremental-Fortress/assets/110744155/95356da6-357d-49f6-9206-6d70bca2d8a6)

**Comment by kurwabomber** [comment]
im guessing this is some kind of thing with sigsegv mod? incremental doesn't do anything with disguises

**Comment by kurwabomber** [comment]
technically was a tf2 bug (disguising technically gives you the weapons?), fixed in next release
