### ISSUE TITLE
Mini sentry particle stacking

### ISSUE THREAD

**Issue by ChaseTownsend** [kurwabomber/Incremental-Fortress#42]
when shooting a mini sentry into a func_visualizer and it self destructs it creates a particle that will almost never go away
it brought me from around 150 fps to less than 5 when looking in it and down to 11 when loading it
![20240620112726_1](https://github.com/kurwabomber/Incremental-Fortress/assets/110744155/131e3656-48f4-4a1b-96e7-eeb33720e44d)

**Comment by kurwabomber** [comment]
client sided issue

**Comment by Cake25217** [comment]
snd_restart in console usually cleans up any persistent particles and sounds, helps out

**Comment by kurwabomber** [comment]
Disabled the particles for now, not sure if any replacement is in mind or if there will be any
